// Code generated by goyacc -o compiler/parser.go compiler/parser.go.y. DO NOT EDIT.

//line compiler/parser.go.y:2
// プログラムのヘッダを指定
package compiler

import __yyfmt__ "fmt"

//line compiler/parser.go.y:3

import (
	"fmt"
	"ks2/compiler/ast"
	cm "ks2/compiler/common"
	"ks2/compiler/vm"
)

var driver *vm.Driver
var lexer *Lexer

//line compiler/parser.go.y:17
type yySymType struct {
	yys  int
	ival int
	fval float32
	sval string

	node       vm.INode
	nodes      []vm.INode
	assign     *ast.Assign
	argList    []*vm.Argument
	argument   *vm.Argument
	stateBlock vm.IStateBlock
	statement  vm.IStatement
}

const INUM = 57346
const FNUM = 57347
const IDENTIFIER = 57348
const STRING_LITERAL = 57349
const PLUS = 57350
const MINUS = 57351
const ASTARISK = 57352
const SLASH = 57353
const PERCENT = 57354
const P_EQ = 57355
const M_EQ = 57356
const A_EQ = 57357
const S_EQ = 57358
const EQ = 57359
const NEQ = 57360
const GT = 57361
const GE = 57362
const LT = 57363
const LE = 57364
const AND = 57365
const OR = 57366
const INCR = 57367
const DECR = 57368
const ASSIGN = 57369
const VAR = 57370
const INT = 57371
const FLOAT = 57372
const STRING = 57373
const VOID = 57374
const IF = 57375
const ELSE = 57376
const SWITCH = 57377
const CASE = 57378
const DEFAULT = 57379
const FALLTHROUGH = 57380
const FOR = 57381
const BREAK = 57382
const CONTINUE = 57383
const FUNC = 57384
const RETURN = 57385
const IMPORT = 57386
const TYPE = 57387
const STRUCT = 57388
const SYSCALL = 57389
const EOL = 57390
const NEG = 57391

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"INUM",
	"FNUM",
	"IDENTIFIER",
	"STRING_LITERAL",
	"PLUS",
	"MINUS",
	"ASTARISK",
	"SLASH",
	"PERCENT",
	"P_EQ",
	"M_EQ",
	"A_EQ",
	"S_EQ",
	"EQ",
	"NEQ",
	"GT",
	"GE",
	"LT",
	"LE",
	"AND",
	"OR",
	"INCR",
	"DECR",
	"ASSIGN",
	"VAR",
	"INT",
	"FLOAT",
	"STRING",
	"VOID",
	"IF",
	"ELSE",
	"SWITCH",
	"CASE",
	"DEFAULT",
	"FALLTHROUGH",
	"FOR",
	"BREAK",
	"CONTINUE",
	"FUNC",
	"RETURN",
	"IMPORT",
	"TYPE",
	"STRUCT",
	"SYSCALL",
	"EOL",
	"'('",
	"')'",
	"'{'",
	"'}'",
	"'['",
	"']'",
	"','",
	"':'",
	"';'",
	"'.'",
	"NEG",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line compiler/parser.go.y:216

func Parse(filename string, source string) int {

	err := &cm.ErrorHandler{ErrorCount: 0, WarningCount: 0}
	driver = new(vm.Driver)
	driver.Init(filename, err)

	// パース処理
	lexer = &Lexer{src: source, position: 0, readPosition: 0, line: 1, filename: filename, err: err}
	yyParse(lexer)

	// ラベル設定
	driver.LabelSettings()

	fmt.Println("Parse End.")

	// パース結果出力
	driver.Dump()

	return 0
}

// 外部用
func GetErrorCount() int {
	return driver.Err.ErrorCount
}
func GetWarningCount() int {
	return driver.Err.WarningCount
}

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 69,
	17, 0,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	-2, 46,
	-1, 70,
	17, 0,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	-2, 47,
	-1, 71,
	17, 0,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	-2, 48,
	-1, 72,
	17, 0,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	-2, 49,
	-1, 73,
	17, 0,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	-2, 50,
	-1, 74,
	17, 0,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	-2, 51,
	-1, 90,
	48, 23,
	-2, 39,
	-1, 94,
	48, 28,
	-2, 40,
}

const yyPrivate = 57344

const yyLast = 287

var yyAct = [...]int{
	78, 77, 62, 89, 15, 30, 31, 82, 124, 99,
	23, 8, 95, 100, 100, 24, 34, 35, 29, 33,
	61, 28, 3, 26, 63, 7, 25, 10, 11, 58,
	63, 6, 6, 60, 115, 112, 34, 35, 97, 33,
	59, 28, 14, 121, 64, 65, 66, 67, 68, 69,
	70, 71, 72, 73, 74, 75, 76, 59, 122, 36,
	98, 32, 80, 22, 96, 95, 16, 17, 18, 90,
	94, 38, 39, 40, 41, 93, 45, 46, 47, 36,
	6, 32, 96, 5, 102, 113, 83, 90, 94, 103,
	20, 56, 57, 21, 110, 119, 111, 16, 17, 18,
	13, 114, 56, 57, 83, 12, 4, 104, 105, 106,
	107, 108, 109, 117, 116, 42, 1, 120, 118, 2,
	123, 9, 91, 127, 125, 126, 43, 44, 45, 46,
	47, 19, 88, 87, 86, 48, 49, 50, 51, 52,
	53, 54, 55, 56, 57, 43, 44, 45, 46, 47,
	85, 84, 81, 92, 48, 49, 50, 51, 52, 53,
	54, 55, 56, 57, 43, 44, 45, 46, 47, 27,
	37, 0, 101, 48, 49, 50, 51, 52, 53, 54,
	55, 56, 57, 0, 34, 35, 97, 33, 63, 28,
	0, 0, 43, 44, 45, 46, 47, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 79, 0, 98, 56,
	57, 0, 0, 95, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 93, 0, 0, 0, 36, 6, 32,
	43, 44, 45, 46, 47, 0, 0, 0, 0, 48,
	49, 50, 51, 52, 53, 54, 55, 56, 57, 43,
	44, 45, 46, 47, 0, 0, 0, 0, 48, 49,
	50, 51, 52, 53, 54, 0, 56, 57, 43, 44,
	45, 46, 47, 0, 0, 0, 0, 48, 49, 50,
	51, 52, 53, 0, 0, 56, 57,
}

var yyPact = [...]int{
	-17, -17, -1000, -1000, -16, -16, -1000, 99, 94, -1000,
	-1000, -1000, -7, 37, 87, 36, -1000, -1000, -1000, -40,
	-1000, 37, 12, 42, 87, -1000, 222, -1000, 12, -9,
	-1000, -1000, 12, -1000, -1000, -1000, -33, -27, -1000, -1000,
	-1000, -1000, -1000, 12, 12, 12, 12, 12, 12, 12,
	12, 12, 12, 12, 12, 12, -1000, -1000, -1000, 12,
	156, 12, -1000, 180, 66, 66, 77, 77, 77, 184,
	184, 184, 184, 184, 184, 260, 241, -41, 222, -1000,
	118, 32, -1000, -1000, -16, -16, -16, -16, -16, -16,
	-1000, -1000, -1000, 12, -1000, 12, 222, 8, 79, -1000,
	12, -15, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	222, 137, 12, 68, 222, 12, 9, 222, 31, 12,
	-42, -21, 12, 222, -1000, -1000, -1000, 222,
}

var yyPgo = [...]int{
	0, 4, 170, 0, 169, 153, 6, 5, 152, 7,
	151, 150, 134, 133, 132, 2, 3, 90, 131, 1,
	122, 116, 119, 22, 106, 83,
}

var yyR1 = [...]int{
	0, 21, 21, 22, 22, 22, 25, 25, 24, 18,
	18, 18, 17, 15, 8, 8, 9, 9, 9, 9,
	9, 9, 9, 10, 11, 12, 13, 13, 14, 16,
	16, 16, 20, 5, 5, 5, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 7, 7, 6, 6, 19,
	19, 19, 4, 4, 4, 1, 1, 1, 2, 2,
	2, 2, 2, 23,
}

var yyR2 = [...]int{
	0, 1, 2, 1, 2, 2, 3, 5, 7, 0,
	1, 3, 2, 3, 1, 2, 1, 2, 2, 2,
	2, 2, 2, 1, 1, 1, 1, 2, 1, 3,
	5, 5, 3, 3, 5, 4, 1, 2, 1, 1,
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 2, 2, 4, 7, 0,
	1, 3, 1, 1, 1, 1, 1, 1, 0, 1,
	1, 1, 1, 1,
}

var yyChk = [...]int{
	-1000, -21, -22, -23, -24, -25, 48, 42, 28, -22,
	-23, -23, 6, 6, 49, -1, 29, 30, 31, -18,
	-17, 6, 27, 50, 55, -1, -3, -4, 9, 6,
	-7, -6, 49, 7, 4, 5, 47, -2, 29, 30,
	31, 32, -17, 8, 9, 10, 11, 12, 17, 18,
	19, 20, 21, 22, 23, 24, 25, 26, -3, 49,
	-3, 53, -15, 51, -3, -3, -3, -3, -3, -3,
	-3, -3, -3, -3, -3, -3, -3, -19, -3, 50,
	-3, -8, -9, -23, -10, -11, -12, -13, -14, -16,
	-7, -20, -5, 43, -6, 33, -3, 6, 28, 50,
	55, 54, 52, -9, -23, -23, -23, -23, -23, -23,
	-3, -3, 27, 6, -3, 49, -15, -3, -1, 27,
	-19, 34, 27, -3, 50, -15, -16, -3,
}

var yyDef = [...]int{
	0, -2, 1, 3, 0, 0, 73, 0, 0, 2,
	4, 5, 0, 0, 9, 6, 65, 66, 67, 0,
	10, 0, 0, 68, 0, 12, 7, 36, 0, 38,
	39, 40, 0, 62, 63, 64, 0, 0, 69, 70,
	71, 72, 11, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 55, 56, 37, 59,
	0, 0, 8, 0, 41, 42, 43, 44, 45, -2,
	-2, -2, -2, -2, -2, 52, 53, 0, 60, 54,
	0, 0, 14, 16, 0, 0, 0, 0, 0, 0,
	-2, 24, 25, 26, -2, 0, 0, 38, 0, 57,
	0, 0, 13, 15, 17, 18, 19, 20, 21, 22,
	27, 0, 0, 0, 61, 59, 29, 32, 33, 0,
	0, 0, 0, 35, 58, 30, 31, 34,
}

var yyTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	49, 50, 3, 3, 55, 3, 58, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 56, 57,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 53, 3, 54, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 51, 3, 52,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 59,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:92
		{
			driver.VariableTable.DefineInLocal(lexer.line, yyDollar[2].sval, yyDollar[3].ival)
		}
	case 7:
		yyDollar = yyS[yypt-5 : yypt+1]
//line compiler/parser.go.y:93
		{
			driver.Err.LogError(driver.Filename, lexer.line, cm.ERR_0026, "")
		}
	case 8:
		yyDollar = yyS[yypt-7 : yypt+1]
//line compiler/parser.go.y:96
		{
			driver.AddFunction(lexer.line, yyDollar[6].ival, yyDollar[2].sval, yyDollar[4].argList, yyDollar[7].statement)
		}
	case 9:
		yyDollar = yyS[yypt-0 : yypt+1]
//line compiler/parser.go.y:99
		{
			yyVAL.argList = make([]*vm.Argument, 0)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:100
		{
			yyVAL.argList = []*vm.Argument{yyDollar[1].argument}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:101
		{
			yyVAL.argList = append(yyDollar[1].argList, yyDollar[3].argument)
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:104
		{
			yyVAL.argument = &vm.Argument{Name: yyDollar[1].sval, VarType: yyDollar[2].ival}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:110
		{
			yyVAL.statement = ast.MakeCompoundStatement(yyDollar[2].stateBlock)
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:113
		{
			s := new(ast.StateBlock)
			yyVAL.stateBlock = s.AddStates(yyDollar[1].statement)
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:114
		{
			yyVAL.stateBlock = yyDollar[1].stateBlock.AddStates(yyDollar[2].statement)
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:117
		{
			yyVAL.statement = nil
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:118
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:119
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:120
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:121
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:122
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:123
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:126
		{
			yyVAL.statement = ast.MakeExprStatement(yyDollar[1].node, driver)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:129
		{
			yyVAL.statement = ast.MakeAssignStatement(yyDollar[1].assign)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:132
		{
			yyVAL.statement = ast.MakeVarDefineStatement(yyDollar[1].node)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:135
		{
			yyVAL.statement = ast.MakeReturnStatement(nil, lexer.line, driver)
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:136
		{
			yyVAL.statement = ast.MakeReturnStatement(yyDollar[2].node, lexer.line, driver)
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:139
		{
			yyVAL.statement = ast.MakeFunctionCallStatement(yyDollar[1].node, driver)
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:142
		{
			yyVAL.statement = ast.MakeIfStatement(yyDollar[2].node, yyDollar[3].statement, nil, lexer.line, driver)
		}
	case 30:
		yyDollar = yyS[yypt-5 : yypt+1]
//line compiler/parser.go.y:143
		{
			yyVAL.statement = ast.MakeIfStatement(yyDollar[2].node, yyDollar[3].statement, yyDollar[5].statement, lexer.line, driver)
		}
	case 31:
		yyDollar = yyS[yypt-5 : yypt+1]
//line compiler/parser.go.y:144
		{
			yyVAL.statement = ast.MakeIfStatement(yyDollar[2].node, yyDollar[3].statement, yyDollar[5].statement, lexer.line, driver)
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:152
		{
			varNode := ast.MakeValueNode(lexer.line, yyDollar[1].sval, driver)
			yyVAL.assign = ast.MakeAssign(lexer.line, varNode, yyDollar[3].node, driver)
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:158
		{
			yyVAL.node = ast.MakeVarDefineNode(lexer.line, yyDollar[2].sval, yyDollar[3].ival, driver)
		}
	case 34:
		yyDollar = yyS[yypt-5 : yypt+1]
//line compiler/parser.go.y:159
		{
			yyVAL.node = ast.MakeVarDefineNodeWithAssign(lexer.line, yyDollar[2].sval, yyDollar[3].ival, yyDollar[5].node, driver)
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
//line compiler/parser.go.y:160
		{
			yyVAL.node = ast.MakeVarDefineNodeWithAssign(lexer.line, yyDollar[2].sval, cm.TYPE_UNKNOWN, yyDollar[4].node, driver)
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:164
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[2].node, nil, ast.OP_NOT, driver)
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:165
		{
			yyVAL.node = ast.MakeValueNode(lexer.line, yyDollar[1].sval, driver)
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:166
		{
			yyVAL.node = yyDollar[1].node
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:167
		{
			yyVAL.node = yyDollar[1].node
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:168
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_ADD, driver)
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:169
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_SUB, driver)
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:170
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_MUL, driver)
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:171
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_DIV, driver)
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:172
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_MOD, driver)
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:173
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_EQUAL, driver)
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:174
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_NEQ, driver)
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:175
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_GT, driver)
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:176
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_GE, driver)
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:177
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_LT, driver)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:178
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_LE, driver)
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:179
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_AND, driver)
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:180
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_OR, driver)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:181
		{
			yyVAL.node = yyDollar[2].node
		}
	case 55:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:184
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, nil, ast.OP_INCR, driver)
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:185
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, nil, ast.OP_DECR, driver)
		}
	case 57:
		yyDollar = yyS[yypt-4 : yypt+1]
//line compiler/parser.go.y:188
		{
			yyVAL.node = ast.MakeFunctionNode(lexer.line, yyDollar[1].sval, yyDollar[3].nodes, driver)
		}
	case 58:
		yyDollar = yyS[yypt-7 : yypt+1]
//line compiler/parser.go.y:189
		{
			yyVAL.node = ast.MakeSysCallNode(lexer.line, yyDollar[3].node, yyDollar[6].nodes, driver)
		}
	case 59:
		yyDollar = yyS[yypt-0 : yypt+1]
//line compiler/parser.go.y:192
		{
			yyVAL.nodes = make([]vm.INode, 0)
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:193
		{
			yyVAL.nodes = []vm.INode{yyDollar[1].node}
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:194
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:197
		{
			yyVAL.node = ast.MakeSvalNode(lexer.line, yyDollar[1].sval, driver)
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:198
		{
			yyVAL.node = ast.MakeIvalNode(lexer.line, yyDollar[1].ival, driver)
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:199
		{
			yyVAL.node = ast.MakeFvalNode(lexer.line, yyDollar[1].fval, driver)
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:202
		{
			yyVAL.ival = cm.TYPE_INTEGER
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:203
		{
			yyVAL.ival = cm.TYPE_FLOAT
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:204
		{
			yyVAL.ival = cm.TYPE_STRING
		}
	case 68:
		yyDollar = yyS[yypt-0 : yypt+1]
//line compiler/parser.go.y:207
		{
			yyVAL.ival = cm.TYPE_VOID
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:208
		{
			yyVAL.ival = cm.TYPE_INTEGER
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:209
		{
			yyVAL.ival = cm.TYPE_FLOAT
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:210
		{
			yyVAL.ival = cm.TYPE_STRING
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:211
		{
			yyVAL.ival = cm.TYPE_VOID
		}
	}
	goto yystack /* stack new state and value */
}
