// Code generated by goyacc -o compiler/parser.go compiler/parser.go.y. DO NOT EDIT.

//line compiler/parser.go.y:2
// プログラムのヘッダを指定
package compiler

import __yyfmt__ "fmt"

//line compiler/parser.go.y:3

import (
	"ks2/compiler/ast"
	cm "ks2/compiler/common"
	"ks2/compiler/vm"
)

var driver *vm.Driver
var lexer *Lexer

//line compiler/parser.go.y:16
type yySymType struct {
	yys  int
	ival int
	fval float32
	sval string

	node  vm.INode
	nodes []vm.INode

	argList  []*vm.Argument
	argument *vm.Argument
	variable *vm.VariableTag
	varlist  []*vm.VariableTag
	vartype  *vm.VariableTypeTag

	valueNode *ast.NValue

	stateBlock     vm.IStateBlock
	statement      vm.IStatement
	caseStatement  *ast.CaseStatement
	caseStatements []*ast.CaseStatement
}

const INUM = 57346
const FNUM = 57347
const IDENTIFIER = 57348
const STRING_LITERAL = 57349
const PLUS = 57350
const MINUS = 57351
const ASTARISK = 57352
const SLASH = 57353
const PERCENT = 57354
const P_EQ = 57355
const M_EQ = 57356
const A_EQ = 57357
const S_EQ = 57358
const MOD_EQ = 57359
const EQ = 57360
const NEQ = 57361
const GT = 57362
const GE = 57363
const LT = 57364
const LE = 57365
const AND = 57366
const OR = 57367
const INCR = 57368
const DECR = 57369
const ASSIGN = 57370
const DECL_ASSIGN = 57371
const VAR = 57372
const INT = 57373
const FLOAT = 57374
const STRING = 57375
const VOID = 57376
const IF = 57377
const ELSE = 57378
const SWITCH = 57379
const CASE = 57380
const DEFAULT = 57381
const FALLTHROUGH = 57382
const FOR = 57383
const BREAK = 57384
const CONTINUE = 57385
const FUNC = 57386
const RETURN = 57387
const IMPORT = 57388
const TYPE = 57389
const STRUCT = 57390
const SYSCALL = 57391
const DUMP = 57392
const EOL = 57393
const NEG = 57394

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"INUM",
	"FNUM",
	"IDENTIFIER",
	"STRING_LITERAL",
	"PLUS",
	"MINUS",
	"ASTARISK",
	"SLASH",
	"PERCENT",
	"P_EQ",
	"M_EQ",
	"A_EQ",
	"S_EQ",
	"MOD_EQ",
	"EQ",
	"NEQ",
	"GT",
	"GE",
	"LT",
	"LE",
	"AND",
	"OR",
	"INCR",
	"DECR",
	"ASSIGN",
	"DECL_ASSIGN",
	"VAR",
	"INT",
	"FLOAT",
	"STRING",
	"VOID",
	"IF",
	"ELSE",
	"SWITCH",
	"CASE",
	"DEFAULT",
	"FALLTHROUGH",
	"FOR",
	"BREAK",
	"CONTINUE",
	"FUNC",
	"RETURN",
	"IMPORT",
	"TYPE",
	"STRUCT",
	"SYSCALL",
	"DUMP",
	"EOL",
	"'('",
	"')'",
	"'{'",
	"'}'",
	"'['",
	"']'",
	"','",
	"':'",
	"';'",
	"'.'",
	"NEG",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line compiler/parser.go.y:328

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 97,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 91,
	-1, 98,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 92,
	-1, 99,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 93,
	-1, 100,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 94,
	-1, 101,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 95,
	-1, 102,
	18, 0,
	19, 0,
	20, 0,
	21, 0,
	22, 0,
	23, 0,
	-2, 96,
	-1, 127,
	51, 41,
	54, 41,
	-2, 84,
	-1, 131,
	51, 46,
	-2, 85,
}

const yyPrivate = 57344

const yyLast = 575

var yyAct = [...]int{
	139, 88, 44, 116, 210, 106, 45, 115, 120, 24,
	46, 128, 113, 179, 182, 80, 112, 81, 129, 81,
	185, 225, 82, 204, 82, 213, 145, 29, 146, 37,
	29, 146, 143, 29, 38, 41, 80, 91, 53, 83,
	81, 33, 224, 39, 78, 82, 89, 55, 79, 191,
	36, 200, 26, 27, 28, 26, 27, 28, 26, 27,
	28, 211, 220, 84, 92, 93, 94, 95, 96, 97,
	98, 99, 100, 101, 102, 103, 104, 192, 217, 132,
	40, 107, 108, 25, 111, 109, 9, 33, 183, 170,
	85, 60, 140, 211, 23, 30, 127, 9, 89, 196,
	131, 144, 86, 29, 201, 34, 9, 188, 19, 49,
	50, 142, 48, 59, 43, 140, 57, 76, 77, 127,
	110, 178, 33, 131, 22, 150, 21, 20, 26, 27,
	28, 163, 9, 164, 166, 141, 140, 169, 203, 90,
	32, 62, 114, 3, 3, 167, 35, 181, 15, 16,
	17, 18, 168, 180, 52, 61, 198, 47, 49, 50,
	51, 48, 2, 43, 14, 8, 184, 7, 186, 6,
	5, 4, 189, 1, 65, 66, 67, 54, 31, 56,
	193, 126, 125, 124, 107, 194, 197, 123, 190, 195,
	76, 77, 202, 122, 121, 119, 118, 56, 205, 117,
	87, 218, 212, 52, 12, 206, 47, 208, 214, 165,
	140, 215, 221, 219, 127, 216, 223, 42, 11, 171,
	10, 13, 58, 222, 0, 9, 0, 0, 140, 140,
	140, 140, 127, 127, 127, 127, 131, 131, 131, 131,
	150, 150, 227, 228, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 151, 152,
	153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
	63, 64, 65, 66, 67, 0, 0, 0, 0, 0,
	68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
	0, 63, 64, 65, 66, 67, 0, 0, 0, 0,
	0, 68, 69, 70, 71, 72, 73, 74, 75, 76,
	77, 0, 49, 50, 142, 48, 0, 43, 0, 0,
	0, 0, 207, 0, 173, 174, 175, 176, 177, 0,
	199, 0, 0, 0, 0, 0, 0, 0, 141, 172,
	0, 209, 226, 132, 0, 136, 0, 0, 137, 133,
	134, 135, 0, 130, 0, 0, 0, 52, 138, 9,
	47, 0, 0, 149, 63, 64, 65, 66, 67, 0,
	0, 0, 0, 0, 68, 69, 70, 71, 72, 73,
	74, 75, 76, 77, 63, 64, 65, 66, 67, 0,
	0, 0, 0, 0, 68, 69, 70, 71, 72, 73,
	74, 75, 76, 77, 63, 64, 65, 66, 67, 0,
	0, 0, 0, 148, 68, 69, 70, 71, 72, 73,
	74, 75, 76, 77, 63, 64, 65, 66, 67, 0,
	0, 0, 0, 147, 68, 69, 70, 71, 72, 73,
	74, 75, 76, 77, 0, 0, 49, 50, 142, 48,
	187, 43, 0, 0, 0, 63, 64, 65, 66, 67,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	89, 0, 141, 76, 77, 0, 0, 132, 0, 136,
	0, 0, 137, 133, 134, 135, 0, 130, 0, 0,
	0, 52, 138, 9, 47, 63, 64, 65, 66, 67,
	0, 0, 0, 0, 0, 68, 69, 70, 71, 72,
	73, 74, 75, 76, 77, 63, 64, 65, 66, 67,
	0, 0, 0, 0, 0, 68, 69, 70, 71, 72,
	73, 74, 75, 76, 77, 63, 64, 65, 66, 67,
	105, 0, 0, 0, 0, 68, 69, 70, 71, 72,
	73, 74, 0, 76, 77, 63, 64, 65, 66, 67,
	0, 0, 0, 0, 0, 68, 69, 70, 71, 72,
	73, 0, 0, 76, 77,
}

var yyPact = [...]int{
	174, 174, -1000, -1000, -1000, 46, 46, 46, 46, -1000,
	101, 121, 120, 118, -1000, -1000, -1000, -1000, -1000, -1000,
	42, 27, 47, 116, 77, 142, -1000, -1000, -1000, -1000,
	-4, -24, -1000, 24, 154, -19, 81, 57, 116, -1000,
	137, 507, -1000, 154, -1000, -1000, -1000, 154, -1000, -1000,
	-1000, -37, -17, 97, 35, -1000, -1000, 46, -8, 135,
	-1000, -1000, -20, 154, 154, 154, 154, 154, 154, 154,
	154, 154, 154, 154, 154, 154, -1000, -1000, -1000, 487,
	154, 154, 114, 154, -1000, -1000, -1000, -1000, -1000, 442,
	-25, 97, 164, 164, 91, 91, 91, 447, 447, 447,
	447, 447, 447, 547, 527, -1000, -27, 507, 376, -1000,
	-39, 356, 308, -1000, -1000, 46, 46, 46, 46, 46,
	46, 46, 46, 46, 46, 46, 46, -1000, -1000, -1000,
	154, -1000, 154, 105, -1000, -1000, 154, -1000, 37, 507,
	311, 115, -16, 97, -1000, -1000, 154, -47, 36, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 507, 416, -40, 416, -1000, -1000, 396,
	100, 154, -1000, -1000, -1000, -1000, -1000, -1000, 21, 154,
	-1000, 507, 114, 154, 63, 154, -1000, 46, -2, 507,
	76, 154, 134, 507, -1000, -30, 44, 262, 55, -1000,
	-1000, 154, 507, -32, -1000, -1000, -1000, 154, 23, -1000,
	-1000, 154, 507, 97, -8, -1000, -1000, -1000, -13, -1000,
	-38, 283, -1000, -1000, -1000, 442, 442, 442, 442,
}

var yyPgo = [...]int{
	0, 9, 222, 219, 0, 217, 18, 10, 6, 11,
	2, 209, 208, 4, 207, 201, 16, 12, 7, 3,
	199, 196, 195, 1, 8, 194, 193, 187, 183, 182,
	181, 116, 178, 5, 177, 47, 173, 162, 142, 171,
	170, 169, 167, 165, 156,
}

var yyR1 = [...]int{
	0, 36, 36, 37, 37, 37, 37, 37, 37, 39,
	41, 41, 41, 42, 40, 32, 32, 32, 31, 31,
	43, 34, 34, 35, 35, 23, 16, 16, 17, 17,
	17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
	17, 18, 19, 20, 21, 21, 22, 24, 24, 24,
	11, 11, 12, 12, 25, 25, 26, 27, 28, 28,
	44, 44, 14, 14, 13, 15, 29, 30, 30, 3,
	3, 3, 3, 3, 3, 9, 6, 6, 6, 6,
	6, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	8, 8, 7, 7, 10, 10, 10, 10, 33, 33,
	33, 5, 5, 5, 1, 1, 1, 1, 2, 2,
	2, 38,
}

var yyR2 = [...]int{
	0, 1, 2, 1, 1, 2, 2, 2, 2, 2,
	3, 5, 6, 6, 7, 0, 1, 3, 2, 5,
	6, 1, 2, 1, 2, 3, 1, 2, 1, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 1, 1, 1, 1, 2, 1, 3, 5, 5,
	1, 1, 1, 1, 7, 3, 1, 1, 6, 7,
	1, 2, 1, 2, 4, 3, 1, 4, 1, 1,
	1, 1, 1, 1, 1, 3, 3, 5, 4, 3,
	6, 1, 2, 1, 1, 1, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	2, 2, 4, 7, 1, 4, 3, 6, 0, 1,
	3, 1, 1, 1, 1, 1, 1, 1, 0, 4,
	1, 1,
}

var yyChk = [...]int{
	-1000, -36, -37, -38, -39, -40, -41, -42, -43, 51,
	46, 44, 30, 47, -37, -38, -38, -38, -38, 7,
	6, 6, 6, 52, -1, 56, 31, 32, 33, 6,
	48, -32, -31, 6, 28, 4, 54, 53, 58, -1,
	56, -4, -5, 9, -10, -8, -7, 52, 7, 4,
	5, 6, 49, 57, -34, -35, -38, -31, -2, 56,
	34, -31, 4, 8, 9, 10, 11, 12, 18, 19,
	20, 21, 22, 23, 24, 25, 26, 27, -4, -4,
	52, 56, 61, 56, -1, 55, -35, -38, -23, 54,
	4, 57, -4, -4, -4, -4, -4, -4, -4, -4,
	-4, -4, -4, -4, -4, 53, -33, -4, -4, -10,
	6, -4, -16, -17, -38, -18, -19, -20, -21, -22,
	-24, -25, -26, -27, -28, -29, -30, -8, -9, -6,
	45, -7, 35, 41, 42, 43, 37, 40, 50, -4,
	-10, 30, 6, 57, -1, 53, 58, 57, 57, 55,
	-17, -38, -38, -38, -38, -38, -38, -38, -38, -38,
	-38, -38, -38, -4, -4, -11, -4, -9, -6, -4,
	52, -3, 28, 13, 14, 15, 16, 17, 6, 29,
	-1, -4, 61, 52, -23, 60, -23, 54, 7, -4,
	-1, 28, 56, -4, -10, -33, 36, -4, -44, -38,
	53, 28, -4, 4, 53, -23, -24, 60, -14, -38,
	-13, 38, -4, 57, -12, -19, -18, 55, -15, -13,
	39, -4, -1, -23, 55, 59, 59, -16, -16,
}

var yyDef = [...]int{
	0, -2, 1, 3, 4, 0, 0, 0, 0, 121,
	0, 0, 0, 0, 2, 5, 6, 7, 8, 9,
	0, 0, 0, 15, 10, 0, 114, 115, 116, 117,
	0, 0, 16, 0, 0, 0, 0, 118, 0, 18,
	0, 11, 81, 0, 83, 84, 85, 0, 111, 112,
	113, 104, 0, 0, 0, 21, 23, 0, 13, 0,
	120, 17, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 100, 101, 82, 0,
	108, 0, 0, 0, 12, 20, 22, 24, 14, 0,
	0, 0, 86, 87, 88, 89, 90, -2, -2, -2,
	-2, -2, -2, 97, 98, 99, 0, 109, 0, 106,
	104, 0, 0, 26, 28, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, -2, 42, 43,
	44, -2, 0, 0, 56, 57, 0, 66, 68, 0,
	83, 0, 104, 0, 19, 102, 0, 105, 0, 25,
	27, 29, 30, 31, 32, 33, 34, 35, 36, 37,
	38, 39, 40, 45, 0, 0, 0, 50, 51, 0,
	0, 0, 69, 70, 71, 72, 73, 74, 0, 0,
	119, 110, 0, 108, 47, 0, 55, 0, 0, 75,
	76, 0, 0, 79, 107, 0, 0, 0, 0, 60,
	67, 0, 78, 0, 103, 48, 49, 0, 0, 61,
	62, 0, 77, 0, 0, 52, 53, 58, 0, 63,
	0, 0, 80, 54, 59, 0, 0, 65, 64,
}

var yyTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	52, 53, 3, 3, 58, 3, 61, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 59, 60,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 56, 3, 57, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 54, 3, 55,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	62,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:119
		{
			ImportFile(yyDollar[2].sval)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:122
		{
			driver.VariableTable.DefineValue(lexer.line, yyDollar[2].sval, yyDollar[3].vartype, false, 1)
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line compiler/parser.go.y:123
		{
			driver.Err.LogError(driver.Filename, lexer.line, cm.ERR_0026, "")
		}
	case 12:
		yyDollar = yyS[yypt-6 : yypt+1]
//line compiler/parser.go.y:124
		{
			driver.VariableTable.DefineValue(lexer.line, yyDollar[2].sval, yyDollar[6].vartype, false, yyDollar[4].ival)
		}
	case 13:
		yyDollar = yyS[yypt-6 : yypt+1]
//line compiler/parser.go.y:127
		{
			driver.DecralateFunction(lexer.line, yyDollar[6].variable, yyDollar[2].sval, yyDollar[4].argList)
		}
	case 14:
		yyDollar = yyS[yypt-7 : yypt+1]
//line compiler/parser.go.y:130
		{
			driver.AddFunction(lexer.line, yyDollar[6].variable, yyDollar[2].sval, yyDollar[4].argList, yyDollar[7].statement)
		}
	case 15:
		yyDollar = yyS[yypt-0 : yypt+1]
//line compiler/parser.go.y:133
		{
			yyVAL.argList = make([]*vm.Argument, 0)
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:134
		{
			yyVAL.argList = []*vm.Argument{yyDollar[1].argument}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:135
		{
			yyVAL.argList = append(yyDollar[1].argList, yyDollar[3].argument)
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:138
		{
			yyVAL.argument = vm.MakeArgument(yyDollar[1].sval, yyDollar[2].vartype, false, 1)
		}
	case 19:
		yyDollar = yyS[yypt-5 : yypt+1]
//line compiler/parser.go.y:139
		{
			yyVAL.argument = vm.MakeArgument(yyDollar[1].sval, yyDollar[5].vartype, false, yyDollar[3].ival)
		}
	case 20:
		yyDollar = yyS[yypt-6 : yypt+1]
//line compiler/parser.go.y:142
		{
			driver.AddType(yyDollar[2].sval, yyDollar[5].varlist, lexer.line)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:145
		{
			t := make([]*vm.VariableTag, 0)
			if yyDollar[1].variable != nil {
				t = append(t, yyDollar[1].variable)
			}
			yyVAL.varlist = t
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:152
		{
			if yyDollar[2].variable != nil {
				yyVAL.varlist = append(yyDollar[1].varlist, yyDollar[2].variable)
			} else {
				yyVAL.varlist = yyDollar[1].varlist
			}
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:155
		{
			yyVAL.variable = nil
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:156
		{
			yyVAL.variable = vm.MakeVariableTag(yyDollar[1].argument.Name, yyDollar[1].argument.VarType, yyDollar[1].argument.IsPointer, yyDollar[1].argument.ArraySize, driver)
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:162
		{
			yyVAL.statement = ast.MakeCompoundStatement(yyDollar[2].stateBlock)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:165
		{
			s := new(ast.StateBlock)
			yyVAL.stateBlock = s.AddStates(yyDollar[1].statement)
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:166
		{
			yyVAL.stateBlock = yyDollar[1].stateBlock.AddStates(yyDollar[2].statement)
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:169
		{
			yyVAL.statement = nil
		}
	case 29:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:170
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:171
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:172
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:173
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 33:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:174
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:175
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:176
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:177
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:178
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:179
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:180
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:181
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:184
		{
			yyVAL.statement = ast.MakeExprStatement(yyDollar[1].node, driver)
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:187
		{
			yyVAL.statement = ast.MakeAssignStatement(yyDollar[1].node)
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:190
		{
			yyVAL.statement = ast.MakeVarDefineStatement(yyDollar[1].node)
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:193
		{
			yyVAL.statement = ast.MakeReturnStatement(nil, lexer.line, driver)
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:194
		{
			yyVAL.statement = ast.MakeReturnStatement(yyDollar[2].node, lexer.line, driver)
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:197
		{
			yyVAL.statement = ast.MakeFunctionCallStatement(yyDollar[1].node, driver)
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:200
		{
			yyVAL.statement = ast.MakeIfStatement(yyDollar[2].node, yyDollar[3].statement, nil, lexer.line, driver)
		}
	case 48:
		yyDollar = yyS[yypt-5 : yypt+1]
//line compiler/parser.go.y:201
		{
			yyVAL.statement = ast.MakeIfStatement(yyDollar[2].node, yyDollar[3].statement, yyDollar[5].statement, lexer.line, driver)
		}
	case 49:
		yyDollar = yyS[yypt-5 : yypt+1]
//line compiler/parser.go.y:202
		{
			yyVAL.statement = ast.MakeIfStatement(yyDollar[2].node, yyDollar[3].statement, yyDollar[5].statement, lexer.line, driver)
		}
	case 54:
		yyDollar = yyS[yypt-7 : yypt+1]
//line compiler/parser.go.y:213
		{
			yyVAL.statement = ast.MakeForStatement(yyDollar[2].node, yyDollar[4].node, yyDollar[6].statement, yyDollar[7].statement, lexer.line, driver)
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:214
		{
			yyVAL.statement = ast.MakeWhileStatement(yyDollar[2].node, yyDollar[3].statement, lexer.line, driver)
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:217
		{
			yyVAL.statement = ast.MakeBreakStatement(lexer.line, driver)
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:220
		{
			yyVAL.statement = ast.MakeContinueStatement(lexer.line, driver)
		}
	case 58:
		yyDollar = yyS[yypt-6 : yypt+1]
//line compiler/parser.go.y:223
		{
			yyVAL.statement = ast.MakeSwitchStatement(yyDollar[2].node, yyDollar[5].caseStatements, nil, lexer.line, driver)
		}
	case 59:
		yyDollar = yyS[yypt-7 : yypt+1]
//line compiler/parser.go.y:224
		{
			yyVAL.statement = ast.MakeSwitchStatement(yyDollar[2].node, yyDollar[5].caseStatements, yyDollar[6].statement, lexer.line, driver)
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:231
		{
			yyVAL.caseStatements = []*ast.CaseStatement{yyDollar[1].caseStatement}
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:232
		{
			yyVAL.caseStatements = append(yyDollar[1].caseStatements, yyDollar[2].caseStatement)
		}
	case 64:
		yyDollar = yyS[yypt-4 : yypt+1]
//line compiler/parser.go.y:235
		{
			yyVAL.caseStatement = ast.MakeCaseStatement(yyDollar[2].node, ast.MakeCompoundStatement(yyDollar[4].stateBlock), lexer.line, driver)
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:238
		{
			yyVAL.statement = ast.MakeCompoundStatement(yyDollar[3].stateBlock)
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:241
		{
			yyVAL.statement = ast.MakeFallThroughStatement(lexer.line, driver)
		}
	case 67:
		yyDollar = yyS[yypt-4 : yypt+1]
//line compiler/parser.go.y:244
		{
			yyVAL.statement = ast.MakeDumpStatement(yyDollar[3].sval, lexer.line, driver)
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:245
		{
			yyVAL.statement = ast.MakeDumpStatement("", lexer.line, driver)
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:252
		{
			yyVAL.ival = ast.OP_ASSIGN
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:253
		{
			yyVAL.ival = ast.OP_ADD_ASSIGN
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:254
		{
			yyVAL.ival = ast.OP_SUB_ASSIGN
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:255
		{
			yyVAL.ival = ast.OP_MUL_ASSIGN
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:256
		{
			yyVAL.ival = ast.OP_DIV_ASSIGN
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:257
		{
			yyVAL.ival = ast.OP_MOD_ASSIGN
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:260
		{
			yyVAL.node = ast.MakeAssign(lexer.line, yyDollar[1].valueNode, yyDollar[3].node, yyDollar[2].ival, driver)
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:263
		{
			yyVAL.node = ast.MakeVarDefineNode(lexer.line, yyDollar[2].sval, yyDollar[3].vartype, false, 1, driver)
		}
	case 77:
		yyDollar = yyS[yypt-5 : yypt+1]
//line compiler/parser.go.y:264
		{
			yyVAL.node = ast.MakeVarDefineNodeWithAssign(lexer.line, yyDollar[2].sval, yyDollar[3].vartype, yyDollar[5].node, driver)
		}
	case 78:
		yyDollar = yyS[yypt-4 : yypt+1]
//line compiler/parser.go.y:265
		{
			yyVAL.node = ast.MakeVarDefineNodeWithAssign(lexer.line, yyDollar[2].sval, driver.GetType("unknown", lexer.line), yyDollar[4].node, driver)
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:266
		{
			yyVAL.node = ast.MakeVarDefineNodeWithAssign(lexer.line, yyDollar[1].sval, driver.GetType("unknown", lexer.line), yyDollar[3].node, driver)
		}
	case 80:
		yyDollar = yyS[yypt-6 : yypt+1]
//line compiler/parser.go.y:267
		{
			yyVAL.node = ast.MakeVarDefineNode(lexer.line, yyDollar[2].sval, yyDollar[6].vartype, false, yyDollar[4].ival, driver)
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:271
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[2].node, nil, ast.OP_NOT, driver)
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:272
		{
			yyVAL.node = yyDollar[1].valueNode
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:273
		{
			yyVAL.node = yyDollar[1].node
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:274
		{
			yyVAL.node = yyDollar[1].node
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:275
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_ADD, driver)
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:276
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_SUB, driver)
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:277
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_MUL, driver)
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:278
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_DIV, driver)
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:279
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_MOD, driver)
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:280
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_EQUAL, driver)
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:281
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_NEQ, driver)
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:282
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_GT, driver)
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:283
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_GE, driver)
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:284
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_LT, driver)
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:285
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_LE, driver)
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:286
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_AND, driver)
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:287
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, yyDollar[3].node, ast.OP_OR, driver)
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:288
		{
			yyVAL.node = yyDollar[2].node
		}
	case 100:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:291
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, nil, ast.OP_INCR, driver)
		}
	case 101:
		yyDollar = yyS[yypt-2 : yypt+1]
//line compiler/parser.go.y:292
		{
			yyVAL.node = ast.MakeExprNode(lexer.line, yyDollar[1].node, nil, ast.OP_DECR, driver)
		}
	case 102:
		yyDollar = yyS[yypt-4 : yypt+1]
//line compiler/parser.go.y:295
		{
			yyVAL.node = ast.MakeFunctionNode(lexer.line, yyDollar[1].sval, yyDollar[3].nodes, driver)
		}
	case 103:
		yyDollar = yyS[yypt-7 : yypt+1]
//line compiler/parser.go.y:296
		{
			yyVAL.node = ast.MakeSysCallNode(lexer.line, yyDollar[3].node, yyDollar[6].nodes, driver)
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:299
		{
			yyVAL.valueNode = ast.MakeValueNode(lexer.line, yyDollar[1].sval, driver)
		}
	case 105:
		yyDollar = yyS[yypt-4 : yypt+1]
//line compiler/parser.go.y:300
		{
			yyVAL.valueNode = ast.MakeArrayValueNode(lexer.line, yyDollar[1].sval, yyDollar[3].node, driver)
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:301
		{
			yyVAL.valueNode = ast.MakeMemberValueNode(lexer.line, yyDollar[1].sval, yyDollar[3].valueNode, driver)
		}
	case 107:
		yyDollar = yyS[yypt-6 : yypt+1]
//line compiler/parser.go.y:302
		{
			yyVAL.valueNode = ast.MakeArrayMemberValueNode(lexer.line, yyDollar[1].sval, yyDollar[3].node, yyDollar[6].valueNode, driver)
		}
	case 108:
		yyDollar = yyS[yypt-0 : yypt+1]
//line compiler/parser.go.y:305
		{
			yyVAL.nodes = make([]vm.INode, 0)
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:306
		{
			yyVAL.nodes = []vm.INode{yyDollar[1].node}
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
//line compiler/parser.go.y:307
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:310
		{
			yyVAL.node = ast.MakeSvalNode(lexer.line, yyDollar[1].sval, driver)
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:311
		{
			yyVAL.node = ast.MakeIvalNode(lexer.line, yyDollar[1].ival, driver)
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:312
		{
			yyVAL.node = ast.MakeFvalNode(lexer.line, yyDollar[1].fval, driver)
		}
	case 114:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:315
		{
			yyVAL.vartype = driver.GetType("int", lexer.line)
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:316
		{
			yyVAL.vartype = driver.GetType("float", lexer.line)
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:317
		{
			yyVAL.vartype = driver.GetType("string", lexer.line)
		}
	case 117:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:318
		{
			yyVAL.vartype = driver.GetType(yyDollar[1].sval, lexer.line)
		}
	case 118:
		yyDollar = yyS[yypt-0 : yypt+1]
//line compiler/parser.go.y:321
		{
			yyVAL.variable = nil
		}
	case 119:
		yyDollar = yyS[yypt-4 : yypt+1]
//line compiler/parser.go.y:322
		{
			yyVAL.variable = vm.MakeVariableTag("", yyDollar[4].vartype, false, yyDollar[2].ival, driver)
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
//line compiler/parser.go.y:323
		{
			yyVAL.variable = nil
		}
	}
	goto yystack /* stack new state and value */
}
